version: 2.1
jobs:
  bobby:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          name: The First Step
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'
  joselo:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run: echo 'Doble problema'
  workflows:
    version: 2
    bobby_joselo:
      jobs:
        - bobby
        - joselo